app = "fenix-ivdev"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  # Disable SSR at first deploy for simplicity; can enable later
  INERTIA_SSR_ENABLED = "false"
  # Avoid DB access during release_command
  CACHE_STORE = "file"
  SESSION_DRIVER = "file"
  APP_URL = "https://fenix.ivaliev.dev"
  ASSET_URL = "https://fenix.ivaliev.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 40
    hard_limit = 60

  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[http_service.checks]]
    name = "web"
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    method = "GET"
    path = "/up"
    protocol = "http"

[deploy]
  release_command = "sh -lc 'php artisan package:discover --ansi && php artisan migrate --force && php artisan optimize'"
