name: tests

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  php-tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.4
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: fenix_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mariadb-admin ping -h 127.0.0.1 -uroot -proot || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Copy env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Wait for MariaDB
        run: |
          for i in {1..30}; do
            (echo >/dev/tcp/127.0.0.1/3306) >/dev/null 2>&1 && break
            sleep 1
          done

      - name: Run tests
        env:
          DB_CONNECTION: mariadb
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: fenix_test
          DB_USERNAME: root
          DB_PASSWORD: root
        run: vendor/bin/phpunit --colors=always
